### PR TITLE
Revert 33 main

### PR DESCRIPTION
**Pull request by pdy1207**
https://github.com/pdy1207/testhttps://github.com/pdy1207/test

### CODE REVIEW

**Comment by pdy1207** [comment]
https://github.com/pdy1207/test

**Comment by pdy1207** [comment]
https://github.com/pdy1207/Dy.dev

**Comment by pdy1207** [comment]
How should I do it, please explain easily

**Comment by learningssik** [comment]
What do you want?

**Comment by pdy1207** [comment]
https://velog.io/@learningssik/Github-%EC%8B%A0%EC%83%81-%EB%B1%83%EC%A7%80-5%EB%B6%84%EB%A7%8C%EC%97%90-%EC%96%BB%EB%8A%94-%EB%B0%A9%EB%B2%95

**Pull request closed without merging**
